In [2]:
import numpy as np

In [3]:
def mat_ops(mat1, mat2):

    print(f"Mult : {np.multiply(mat1, mat2)}\n"
          f"Dot : {np.dot(mat1, mat2)}")

a=np.matrix([[1,2,3],
[4,5,6],
[7,8,9]])

b = np.matrix([[2,1,5],
[5,1,7],
[6,3,2]])

mat_ops(a, b)

Mult : [[ 2  2 15]
 [20  5 42]
 [42 24 18]]
Dot : [[ 30  12  25]
 [ 69  27  67]
 [108  42 109]]


In [4]:
z = np.mean(a, axis=0)
s = np.mean(a, axis=1)
u = np.mean(a)
f = np.mean(s) + np.mean(z)
print(
    f"Mean Axis 0 = {z}\n"
    f"Mean Axis 1 = {s}\n"
    f"Mean a = {u}\n"
    f"Try mean = {f/2}"
)

Mean Axis 0 = [[4. 5. 6.]]
Mean Axis 1 = [[2.]
 [5.]
 [8.]]
Mean a = 5.0
Try mean = 5.0


In [7]:
def stan_var(_array):

    if np.ndim(_array) == 1:
        return np.mean(_array), np.var(_array), np.std(_array)
    else :
        print(f"Axis 0 : {np.mean(_array,axis=0)}\n"
              f"Axis 1 : {np.mean(_array,axis=1)}\n"
              f"Mean : {np.mean(_array)}\n"
              f"Variance 0: {np.var(_array, axis=0)}\n"
              f"Variance 1 :{np.var(_array, axis=1)}\n"
              f"Standard Variation 0: {np.std(_array, axis=0)}\n"
              f"Standard Variation  1 :{np.std(_array, axis=1)}\n")

j = np.array([1,2,3])

a=np.matrix([[1,2,3],
[4,5,6],
[7,8,9]])

stan_var(a)
stan_var(j)

Axis 0 : [[4. 5. 6.]]
Axis 1 : [[2.]
 [5.]
 [8.]]
Mean : 5.0
Variance 0: [[6. 6. 6.]]
Variance 1 :[[0.66666667]
 [0.66666667]
 [0.66666667]]
Standard Variation 0: [[2.44948974 2.44948974 2.44948974]]
Standard Variation  1 :[[0.81649658]
 [0.81649658]
 [0.81649658]]



(2.0, 0.6666666666666666, 0.816496580927726)

In [8]:
# Distribution Research

In [11]:
def cov_cor(v1, v2):

    cov = np.cov(v1,v2)
    cor = np.corrcoef(v1,v2)
    return cov,cor

cov_cor([6,4,9], [4,0,9])

(array([[ 6.33333333, 11.33333333],
        [11.33333333, 20.33333333]]),
 array([[1.        , 0.99870494],
        [0.99870494, 1.        ]]))

In [13]:
def mult_(mat,v):

    dot = np.dot(mat,v)
    mean = np.mean(dot)
    std = np.std(dot)
    var = np.var(dot)
    return dot, mean, std, var
j = np.array([1,2,3])

a=np.matrix([[1,2,3],
[4,5,6],
[7,8,9]])
mult_(a, j)

(matrix([[14, 32, 50]]), 32.0, 14.696938456699069, 216.0)